### ISSUE TITLE
BETA Testing Reporter

### ISSUE THREAD

**Issue by compilenix** [beastdestroyer/vscode-firefox-quantum-themes#1]
Could you add some to the readme?

**Comment by beastdestroyer** [comment]
Hi there, seems someone actually stumbled upon this. Well I'm currently working on this at my own pace and balancing this amongst other stuff with school. But I'd be happy to provide some current stuff, by the time you read this, plus minus a few hours perhaps, there should be some. Thanks!

**Comment by compilenix** [comment]
Really nice, thanks!

One more question, is it available on the marketplace?

**Comment by beastdestroyer** [comment]
Soon. I just need to make sure I have support for as many languages as possible (without their extensions), fix a few UI issues and then Dark Theme will be avaliable on the Marketplace. Perhaps a Christmas release who knows :P 

I'm currently uploading screenshots so keep checking the readme, thanks for your interest!

**Comment by compilenix** [comment]
Great, i'm considering switching from [my own adapted dark theme](https://github.com/compilenix/theme-bluloco-dark-plus) to yours.

I'll wait, it's ready when it's ready :smile: 

If you need a "beta tester" let me know :wink:

**Comment by compilenix** [comment]
Uhh nice!

I like it very much. I've made a `git clone` and created a symlink at `~/.vscode/extensions/vscode-firefox-quantum-themes-latest` directly to the git repo, that way i only have to make a `git pull` and reload vscode the see changes made in that branch.

Here is a screenshot i've made with a projekt i recently worked on, feel free to use it if you want:

![image](https://user-images.githubusercontent.com/6356150/48983763-2a2b4c80-f0f3-11e8-9fdd-e76d286e1530.png)

I'll run with this as "my daily driver" and report my experience and suggestions :smile:

**Comment by compilenix** [comment]
One more thing; dont feel required to prioritize this side-projekt higher than you would normally.
I have time and there is no rush :wink:

**Comment by beastdestroyer** [comment]
@compilenix Beta 3 now out, time to `git pull` and fetch origin :P

**Comment by compilenix** [comment]
Yep, i'm already enjoying the changes.

maybe the user should be recommended (in the readme or so) to set `"workbench.editor.highlightModifiedTabs": true`, as this improves visibilty of opened files with changes more but not too much at the same time.

**Comment by compilenix** [comment]
So far, i really like it.
I'm using it at home on my personal systems as well as at work on my workstation.

It was hard in general to find a dark theme which appealed to me, most existing ones are not quite dark enough for my taste. This was also the reason why i created / adapted my own a while ago.

I look forward for future betas and sometime a first release!

**Comment by beastdestroyer** [comment]
Hey @compilenix In the latest build (5), I added support for a few more languages (indicated on the checklist #8 ) but I also started adding in the Light Theme in this version. I am very aware many things are broken and would like your help in finding them. So far it's been a copy and paste effort so yeah :P.

If you do find issues (which I'm sure you would) please open them and prefix the title with [LIGHT] if it's relevant to it. Thanks once again! 

Note: won't be able to get onto it until the next days.

**Comment by beastdestroyer** [comment]
Released Version 7, try taking it from the releases tag, just experimenting with that :P

**Comment by beastdestroyer** [comment]
Guess what my dude @compilenix 
https://marketplace.visualstudio.com/items?itemName=beastdestroyer.firefox-quantum-themes

**Comment by compilenix** [comment]
Yay, Christmas came early this year xD

**Comment by compilenix** [comment]
I've created some minor PR's, take them as a suggestion :)

Except for one PR (#16); this change seems to be required since the trailing `,` in [package.json L8](https://github.com/beastdestroyer/vscode-firefox-quantum-themes/blob/f1369c2f0551112f6ec5e4c69ee193bcd82810c0/package.json#L8) made the package.json technically invalid which resulted in not loading the extension.

**Comment by beastdestroyer** [comment]
I'll see how some of these look and roll back if needed :)

**Comment by beastdestroyer** [comment]
Hey there, since I've basically "released" it on the Marketplace, it's technically official release so closing. You can still beta test from packages released (https://github.com/beastdestroyer/vscode-firefox-quantum-themes/releases), :) If you want to comment, go to #8 as that tracks patches and whatnot up until 1.1.0, thanks! (Also I'll eventually add you into the commit notes, still trying to work out kinks, thanks again!)

**Comment by beastdestroyer** [comment]
Another thing, after realising that I accidentally keep putting people on betas, I've cerated a beta branch for testing, submit pull requests there instead! Updating documentation!
