### ISSUE TITLE
Statusbar font color is differnt

### ISSUE THREAD

**Issue by compilenix** [beastdestroyer/vscode-firefox-quantum-themes#10]
As seen on the bottom in the following screenshots:

![image](https://user-images.githubusercontent.com/6356150/49611875-4658a480-f9a3-11e8-9183-1a8f2313b9eb.png)

and

![image](https://user-images.githubusercontent.com/6356150/49611883-4d7fb280-f9a3-11e8-83e9-3d56898e2e63.png)

**Comment by beastdestroyer** [comment]
After looking at Firefox DevTools, I've noticed that the tabs tend to use this darker grey. As such, classing this as wontfix and reverted the colour of the title bar back, and also changed sidebar titles
