### ISSUE TITLE
Seach & Replace activity bar input fields have no border / low contrast

### ISSUE THREAD

**Issue by compilenix** [beastdestroyer/vscode-firefox-quantum-themes#11]
the input fields only have a border when selected.

no selected input field:
![image](https://user-images.githubusercontent.com/6356150/49612188-27a6dd80-f9a4-11e8-8fb2-b11fe2e78ad0.png)

`files to include` input field is selected:
![image](https://user-images.githubusercontent.com/6356150/49612203-34c3cc80-f9a4-11e8-975a-3750c7a116e3.png)

**Comment by compilenix** [comment]
it's the same for the input fields on the `Source Control`, `Debug` and `Extensions` activity bar

**Comment by beastdestroyer** [comment]
Gotcha, might have to find a light colour/transparent version. I'll refer to DevTools.

**Comment by beastdestroyer** [comment]
Well I've tried a lighter colour, looks a bit odd in my opinion but when Beta 6 rolls out eventually, try use it for yourself. Dropdowns have remained dark. Here's a screenshot
![image](https://user-images.githubusercontent.com/30497573/49663579-11059280-fa47-11e8-997d-9cae7f8c75ea.png)

**Comment by beastdestroyer** [comment]
I haven't released it yet, but if you want to modify colours for yourself, go to the `Quantum Dark.json` file and change the `input.background` property

**Comment by compilenix** [comment]
OK, `#252c33` looks much better.
Thanks :)

**Comment by beastdestroyer** [comment]
Gotcha , looks nice now I've used it for a bit
