### ISSUE TITLE
Debugger toobar has different background color

### ISSUE THREAD

**Issue by compilenix** [beastdestroyer/vscode-firefox-quantum-themes#12]
See here:
![image](https://user-images.githubusercontent.com/6356150/49698337-bee97c00-fbc2-11e8-85ec-6a0f591f907d.png)

**Comment by beastdestroyer** [comment]
Huh, I'll see what is causing that. Probably I missed an option or I put wrong colour..

**Comment by beastdestroyer** [comment]
Fixed in Beta 6, releasing soon :)
