### ISSUE TITLE
Status bar background color washed-out when in debug session

### ISSUE THREAD

**Issue by compilenix** [beastdestroyer/vscode-firefox-quantum-themes#13]
See here:
![image](https://user-images.githubusercontent.com/6356150/49698368-fc4e0980-fbc2-11e8-8035-5bdc832e107f.png)

**Comment by beastdestroyer** [comment]
Changing to the red/orange colour, thanks! (also matches Visual Studio itself, so good choice from me :P)

**Comment by beastdestroyer** [comment]
Accidentally Released Beta 6 without this change, pushed out 7 to get this, tell me what you think in both themes!
