### ISSUE TITLE
[LIGHT] Status bar background and text color washed-out when in debug session

### ISSUE THREAD

**Issue by compilenix** [beastdestroyer/vscode-firefox-quantum-themes#14]
See here
![image](https://user-images.githubusercontent.com/6356150/49698387-4800b300-fbc3-11e8-805b-790f80ef95c4.png)

**Comment by beastdestroyer** [comment]
Thanks, will get to that

**Comment by beastdestroyer** [comment]
Foreground is now white in my build, fixed.
