### ISSUE TITLE
[LIGHT] Activity Items not visible

### ISSUE THREAD

**Issue by compilenix** [beastdestroyer/vscode-firefox-quantum-themes#15]
See here:

![image](https://user-images.githubusercontent.com/6356150/49698426-de34d900-fbc3-11e8-8e8c-27c594c3a3ea.png)

**Comment by beastdestroyer** [comment]
Yeah I fixed that in my build, I literally just copy and pasted for Beta 5, a better polished version is on the way sometime next week :)

**Comment by beastdestroyer** [comment]
Fixed, found a few lingering issues in the case of having only 1 file but that'll be fixed in beta 7 :P
