### ISSUE TITLE
Contrast on Mouse-Over of menus is quite low

### ISSUE THREAD

**Issue by compilenix** [beastdestroyer/vscode-firefox-quantum-themes#2]
In the following screenshot one can see that i've selected the second element from the menu.
Visually it's bearly noticeable.

![image](https://user-images.githubusercontent.com/6356150/48983888-d457a400-f0f4-11e8-9d7d-5197edd4c71a.png)

**Comment by beastdestroyer** [comment]
Brighter now, also changed up the file explorer active/hover, see what you think

**Comment by compilenix** [comment]
yes, on point!
