### ISSUE TITLE
[LIGHT] light yellow

### ISSUE THREAD

**Issue by compilenix** [beastdestroyer/vscode-firefox-quantum-themes#22]
Hmm, the light yellow (`terminal.ansiYellow`) is nearly impossible to notice :/

![image](https://user-images.githubusercontent.com/6356150/50113281-c30c3e00-0241-11e9-9c6f-e240222a555e.png)

The "real" problem is that i've looked at the devtools of firefox and were not able to find that color (`#ffffb4`) used anywhere, but slightly differing colors like:

- `#fdffdf`
![image](https://user-images.githubusercontent.com/6356150/50112953-e2ef3200-0240-11e9-8449-24360e47948a.png)
- `#fffbd6`
![image](https://user-images.githubusercontent.com/6356150/50113034-1e89fc00-0241-11e9-87ec-7264867b43ca.png)

Maybe use a non-devtools color for this?
I've payed around using `#f3e212`.

![image](https://user-images.githubusercontent.com/6356150/50113735-1af77480-0243-11e9-81cd-2ecb70f34313.png)

What do you think?

**Comment by beastdestroyer** [comment]
Ah yes I changed the yellow in the syntax highlighting but forgot for the terminal, I'll get to that in the next day. Just curious, are you still taking the beta releases? :> And yh, I'm most likely gonna use that orangey yellow too

**Comment by compilenix** [comment]
I'm running on the current `beta` branch on all my systems :)

**Comment by beastdestroyer** [comment]
Fixed, beta coming soon!
