### ISSUE TITLE
Theme title is not the same as name of extension

### ISSUE THREAD

**Issue by usernamehw** [beastdestroyer/vscode-firefox-quantum-themes#25]
* Install a theme `Firefox Quantum Themes`
* Open theme picker
* Type `fire`
* Nothing is there

**Comment by usernamehw** [comment]
I have 0 themes installed starting with `fire` ... should probably reevaluate life choices.

**Comment by beastdestroyer** [comment]
Oops, still new to this xD

**Comment by beastdestroyer** [comment]
Fixed :)

**Comment by beastdestroyer** [comment]
Also, I named them quantum just in case the patch didn't get rolled out correctly
