### ISSUE TITLE
Repository Cleanup

### ISSUE THREAD

**Issue by beastdestroyer** [beastdestroyer/vscode-firefox-quantum-themes#27]
This goal is aimed at cleaning up the repo by doing the following

- Screenshots
  - Capture full windows screenshots of the most popular languages in VSCode, without extensions installed
  - Ensure that all screenshots go to the `screenshots` folder
  - Each file is named `language.png`
  - Dark and Light themes side by side per language
  - **Contributions Welcome**

- Test Files
  - These are random code which does nothing (and shouldn't be run on any computer) and there for the purpose of testing syntax highlighting
  - All files for the purpose of screenshotting
  - All test files will be deleted in official release

- Repository
  - Issues/pulls tagged correctly.
  - Issue template
  - Wiki detailing
    - Contribution
    - Installation

Releasing as a 1.1.x update

**Comment by beastdestroyer** [comment]
Hehehe, if you have a good knowledge with file systems, usually quotes fix it, or the classic `%20` non-breaking space (sometimes abbreviated as nbsp) :p but I can rename as necessary

**Comment by usernamehw** [comment]
@beastdestroyer, have you thought about moving test files into a separate repo?

I've seen similar ones in the past. The main point is: it's really hard to maintain it alone (a lot of languages and each language has a lot of constructing parts).

**Comment by beastdestroyer** [comment]
@usernamehw I have actually been thinking of removing the test files completely. The only real purpose I denoted to them was contributor testing anf screenshots, however I realise that contributors, even new ones can easily work out: open a file, set language, type code and see if it works, and eventually I'll finish with the screenshots. Hence I'll be removing them in 1.1.0. 

Updating OP to reflect this
