### ISSUE TITLE
Contrast of comments in the current line is low

### ISSUE THREAD

**Issue by compilenix** [beastdestroyer/vscode-firefox-quantum-themes#3]
The code comment and git blame annotation from GitLens is barely visible if the carret is at that line.

I think it should be possible to define a seperate `background-color` or `color` for the line where the carret curently is.

![image](https://user-images.githubusercontent.com/6356150/48984179-d1f74900-f0f8-11e8-932b-218836a0b815.png)

**Comment by beastdestroyer** [comment]
Yh, I had that issue, I might make it the very dark colour used in the rest of the UI, I will change it to the colour is `#14171a`. I forgot the exact setting in the file, thanks for these, gonna work on these the next day :P

**Comment by compilenix** [comment]
more dark => more nice

**Comment by beastdestroyer** [comment]
\#AllTheDark

**Comment by beastdestroyer** [comment]
Much better right?
![image](https://user-images.githubusercontent.com/30497573/49031090-ef7fed80-f1a0-11e8-8257-32e2317e2233.png)

**Comment by beastdestroyer** [comment]
Looks good to me, closing

**Comment by compilenix** [comment]
Yep, agree
