### ISSUE TITLE
Code font color can't be seen clearly

### ISSUE THREAD

**Issue by 395053994** [beastdestroyer/vscode-firefox-quantum-themes#38]
![2222](https://user-images.githubusercontent.com/27546390/65923856-0c1e2f00-e41d-11e9-9907-dba160f21228.png)
Issue Type: <b>Bug</b>

Code font color can't be seen clearly

Extension version: 1.1.7
VS Code version: Code - Insiders 1.39.0-insider (79978f96d3501f14b235ed0a33a7360772a726a3, 2019-09-30T14:18:14.941Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|9.59GB (4.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by beastdestroyer** [comment]
@395053994 Thanks for letting me know and apologies for the long reply;

Please could you let me know of the following:
Language (java to me, but just to be sure)

Press F1 > Inspect TMscopes (or something like that)
Click onto the broken text
Screenshot/tell me the scopes it mentions

Thanks!

**Comment by beastdestroyer** [comment]
Edit  I have found the root issue and i will publish a package soon alongside some other polishes

**Comment by beastdestroyer** [comment]
Can confirm to be fixed, should be out now
