### ISSUE TITLE
"reload" buttons on extension pane maybe needs another background color

### ISSUE THREAD

**Issue by compilenix** [beastdestroyer/vscode-firefox-quantum-themes#5]
![image](https://user-images.githubusercontent.com/6356150/48987145-7343c680-f11c-11e8-98f0-827d2b5373b9.png)

Maybe a blue-ish or purple-ish color is nice?

**Comment by beastdestroyer** [comment]
Yeah was definitely gonna change that to blue, along with the other buttons

**Comment by beastdestroyer** [comment]
Alright, all buttons now start with a lighter grey and have a blue hover now, much more distringuishable I might argue :)

**Comment by compilenix** [comment]
Yes much better, thanks!
