### ISSUE TITLE
"changed items" badges need another color

### ISSUE THREAD

**Issue by compilenix** [beastdestroyer/vscode-firefox-quantum-themes#6]
![image](https://user-images.githubusercontent.com/6356150/48987207-3deba880-f11d-11e8-8f87-949aa23c3827.png)

i think either the font color or the badge background color should give more contrast.

As for background color, i would suggest blue or yellow / orange.

**Comment by beastdestroyer** [comment]
I'll experiment with this, I personally prefer the current right now. :P

**Comment by compilenix** [comment]
Hm, yes i can see that it fit's into the general theme.
So, feel free to close as won't fix :)

**Comment by beastdestroyer** [comment]
Yh, I've tested with others and looked at DevTools, I find that this colour fits in quite well. This is also similar with other themes ironically enough so yeah it's all good. Feel free to test yourself, just edit `themes/Quantum Dark.json`

**Comment by beastdestroyer** [comment]
Actually, since the change to buttons having a slightly lighter grey, I probably will. change the badge colour also :)

**Comment by beastdestroyer** [comment]
This change has been implemented in my build
