### ISSUE TITLE
Filename color with "errors" not red anymore when currently selected / opened

### ISSUE THREAD

**Issue by compilenix** [beastdestroyer/vscode-firefox-quantum-themes#7]
![image](https://user-images.githubusercontent.com/6356150/48987294-ff0a2280-f11d-11e8-9190-3f732deea2ff.png)

In this example both, `Config.js` and `index.js` have linting errors but because `index.js` is currently selected (or hovered over) the red text color is overwritten by the text color for selected / hovered elements.

**Comment by beastdestroyer** [comment]
I did not notice that at all, thanks!

**Comment by beastdestroyer** [comment]
Well I think the hover issue is gone in my build, but for selected that does happen, even VSCode's Dark+ theme changes the foreground colour to that white/grey, hence I can't do much. Marking as fixed.
