### ISSUE TITLE
Toolbar-Menu font color is differnt

### ISSUE THREAD

**Issue by compilenix** [beastdestroyer/vscode-firefox-quantum-themes#9]
Here one  can see that the font color of the toolbar menu / main menu items are a bit darker / washed out (marked red) as in other parts of the theme (i.e. the explorer filenames)

![image](https://user-images.githubusercontent.com/6356150/49329572-588caa00-f581-11e8-960d-399105aec5c5.png)

**Comment by beastdestroyer** [comment]
Cool, need that uniformity :P
